version: '3.9'
services:
  api:
    image: test_backend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8081:8081
  redis: 
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data

    networks:
      - prologue

volumes:
  redis:
    driver: local

networks:
  prologue:
    driver: bridge